In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
from matminer import PlotlyFig as mmplt

In [4]:
df = pd.read_excel('final_metal_oxide_properties_copy.xlsx', sheet_name='oxide_correlation')

In [5]:
df.head()

,unique_oxides,formation__energy_per_oxygen_ev,t_onset,t_peak_1,t_peak_2,t_peak_3,t_max,t_melt
0,Ac2O3,-8.720482,NaN,NaN,NaN,NaN,NaN,1977.0
1,AgO,-3.385787,NaN,NaN,NaN,NaN,NaN,100.0
2,Ag3O4,-3.200600,NaN,NaN,NaN,NaN,NaN,NaN
3,Ag2O,-3.456287,60.0,112.5,191.3,-,191.3,200.0
4,Al2O3,-8.204621,NaN,NaN,NaN,NaN,NaN,2053.0

In [6]:
df = df[np.isfinite(df['t_melt'])]
df.head()

,unique_oxides,formation__energy_per_oxygen_ev,t_onset,t_peak_1,t_peak_2,t_peak_3,t_max,t_melt
0,Ac2O3,-8.720482,NaN,NaN,NaN,NaN,NaN,1977.0
1,AgO,-3.385787,NaN,NaN,NaN,NaN,NaN,100.0
3,Ag2O,-3.456287,60.0,112.5,191.3,-,191.3,200.0
4,Al2O3,-8.204621,NaN,NaN,NaN,NaN,NaN,2053.0
5,As2O5,-4.674392,NaN,NaN,NaN,NaN,NaN,315.0

In [12]:
pf = mmplt(df, x_title='formation_energy(eV)', y_title='melting_temp')
df.columns
pf.xy(('formation__energy_per_oxygen_ev','t_melt'), labels='unique_oxides', colorscale='Picnic', limits={'x':(-6,-5)})